# Use the base TensorFlow training image

ARG IMAGE_REPO=repository.sabre-gcp.com:9083

# hadolint ignore=DL3007

FROM $IMAGE_REPO/sabre/base-images/ubi9/python-3.11:latest

# Copy requirements and install dependencies (if you have a requirements.txt)

COPY requirements.txt .

RUN python3 -m pip install --no-cache-dir --upgrade pip && \

    python3 -m pip install --no-cache-dir -r requirements.txt

COPY  trainer trainer/

ENTRYPOINT ["python","-m", "trainer.train"]"""

