# Use the base TensorFlow training image

ARG IMAGE_REPO=<add the image repo name>

FROM $IMAGE_REPO/base-images/ubi9/python-3.11:latest

# Copy requirements and install dependencies

COPY requirements.txt.

RUN python3 -m pip install --no-cache-dir --upgrade pip && \

    python3 -m pip install --no-cache-dir -r requirements.txt

COPY  trainer trainer/

ENTRYPOINT ["python","-m", "trainer.train"]"""
