[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_gan_package"
version = "0.1"
description = "GAN for synthetic data"
readme = "README.md"

dependencies = [
  "db-dtypes",
  "tensorflow==2.19.0",
  "pandas",
  "numpy",
  "scikit-learn",
  "psutil",
  "scipy",
  "google-cloud-bigquery",
  "gcsfs",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]
